### ISSUE TITLE
Getting the SHA1 value in Hash

### ISSUE THREAD

**Issue by realmgic** [tessus/db2-hash-routines#14]
Hey,

I really like this solution - but I've got a question.

For compatibility reasons (with the results got in other databases like Oracle, SQL Server and MySQL), I need to get the SHA1 value in a Hex format (like the Hex in SHA256). Is there a way to modify the code to add this function? Is it possible with the tools we already have here? 

Thanks!
Zohar

**Comment by tessus** [comment]
Can you please give me an example. Use the clear text 'test' and post the hash. 

I suspect you're looking for a non seeded hash which is inherently less secure, but it can be used as a key. Yet, sha1 still has a chance of collisions, thus I'd go with sha256. Anyway, I can have a look.

**Comment by realmgic** [comment]
SHA1 value for "test" is "A94A8FE5CCB19BA61C4C0873D391E987982FBBD3" (hex value).
This is the value I get from Oracle, SQL Server, MySQL and general online SHA1 calculators online (for example, http://www.sha1-online.com/ or http://sha1-hash-online.waraxe.us/)

The value I get from your function: "{SHA}mO8HWOaqxvmp4Rl1SMgZC3LJWB0=" which I can only guess that is encoded somehow (i guessed base64, but it didn't decode so I don't know).

The reason we need this, is to compare values between different databases platforms without actually exposing what was the original value. we can live with collisions (we don't care if it happens - false positives are okay).

We can't use SHA2-256 because it did not exist (out of the box) before Oracle 12 and SQL Server 2012.

**Comment by tessus** [comment]
I have to look into it, but I believe I can add a `sha1_hex` UDF and SP.

I'm gonna work on it this weekend. see #15 for additional info.

**Comment by realmgic** [comment]
Thanks! I really appreciate it!

**Comment by tessus** [comment]
added in 536569a652a78d4c0a55ef056a300a8be5db06cc

I still have to update the documentation, web site, and create a new release, but you can already use the latest code to get the `sha1_hex` UDF and SP.

**Comment by tessus** [comment]
@realmgic just in case you missed it. the new release is available here https://github.com/tessus/db2-hash-routines/releases/tag/1.9
