### ISSUE TITLE
Not working after installation

### ISSUE THREAD

**Issue by tsschulz** [tessus/db2-hash-routines#18]
I've a similar problem like at the other request.
My installation seemed to went well. I was connecting to the db first (db2 connect to...) and got an "libary installed successfully."
But when I try a "db2 select SHA256('test') FROM sysibm.sysdummy1" the result is
1                                                      
-------------------------------------------------------
SQL0444N  Die Routine "DB2INST1.SHA256" (spezifischer Name "UDF_SHA256") ist
durch Code in Bibliothek oder Pfad ".../sqllib/function/hash", Funktion
"sha256" implementiert, auf die kein Zugriff möglich ist.  Ursachencode: "4".
SQLSTATE=42724
Or easier: SQL0444N, code 4, SQLSTATE=42724, access to .../sqllib/function/hash isn't possible. I also wonder about "...", because my system don't know this path.

**Comment by tessus** [comment]
Reason code 4 usually means that something couldn't be found. Not necessarily the library itself, but also other lib dependencies.

What ist you instance home directory? (default: /home/db2inst1/sqllib)
Is the file `hash` in `$DB2_HOME/function`? Does it belong to the instance user?
Do you have the APR libs in the ld.so path?
What is the output of `ldd ./hash` (please run in it the function dir).

> Or easier: SQL0444N, code 4, SQLSTATE=42724, access to .../sqllib/function/hash isn't possible. I also wonder about "...", because my system don't know this path.

What does that mean? You don't have an `~/sqllib/function` directory for your db2 instance user?

Do you have a test VM or machine I can connect to? This would go a lot faster this way.

**Comment by tsschulz** [comment]
The instance home directory is indeed /home/db2inst1/sqllib
Also hash is in $DB2_HOME/function and it belongs to the instance user
The APR libs (libapr-1.so) are in the system lib folder, so they are in the ld.so path

 ldd ./hash 
        linux-vdso.so.1 (0x00007ffdfef5e000)
        libdb2.so.1 => /home/db2inst1/sqllib/lib64/libdb2.so.1 (0x00007fdb77250000)
        libapr-1.so.0 => /usr/lib64/libapr-1.so.0 (0x00007fdb7701c000)
        librt.so.1 => /lib64/librt.so.1 (0x00007fdb76e14000)
        libpthread.so.0 => /lib64/libpthread.so.0 (0x00007fdb76bf7000)
        libdl.so.2 => /lib64/libdl.so.2 (0x00007fdb769f3000)
        libaprutil-1.so.0 => /usr/lib64/libaprutil-1.so.0 (0x00007fdb767ca000)
        libldap-2.4.so.2 => /usr/lib64/libldap-2.4.so.2 (0x00007fdb7657e000)
        liblber-2.4.so.2 => /usr/lib64/liblber-2.4.so.2 (0x00007fdb7636f000)
        libdb-4.8.so => /usr/lib64/libdb-4.8.so (0x00007fdb75ff2000)
        libexpat.so.1 => /usr/lib64/libexpat.so.1 (0x00007fdb75dc8000)
        libc.so.6 => /lib64/libc.so.6 (0x00007fdb75a25000)
        libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007fdb757ea000)
        libpam.so.0 => /lib64/libpam.so.0 (0x00007fdb755db000)
        libxml2.so.2 => /usr/lib64/libxml2.so.2 (0x00007fdb75270000)
        libm.so.6 => /lib64/libm.so.6 (0x00007fdb74f73000)
        libdb2dascmn.so.1 => /home/db2inst1/sqllib/lib64/libdb2dascmn.so.1 (0x00007fdb74d46000)
        libdb2g11n.so.1 => /home/db2inst1/sqllib/lib64/libdb2g11n.so.1 (0x00007fdb74361000)
        libdb2genreg.so.1 => /home/db2inst1/sqllib/lib64/libdb2genreg.so.1 (0x00007fdb74119000)
        libdb2install.so.1 => /home/db2inst1/sqllib/lib64/libdb2install.so.1 (0x00007fdb73f05000)
        libdb2locale.so.1 => /home/db2inst1/sqllib/lib64/libdb2locale.so.1 (0x00007fdb73cde000)
        libdb2osse.so.1 => /home/db2inst1/sqllib/lib64/libdb2osse.so.1 (0x00007fdb7351f000)
        libdb2osse_db2.so.1 => /home/db2inst1/sqllib/lib64/libdb2osse_db2.so.1 (0x00007fdb7328c000)
        libdb2sdbin.so.1 => /home/db2inst1/sqllib/lib64/libdb2sdbin.so.1 (0x00007fdb72ff1000)
        libdb2trcapi.so.1 => /home/db2inst1/sqllib/lib64/libdb2trcapi.so.1 (0x00007fdb72dd4000)
        libstdc++.so.6 => /usr/lib64/libstdc++.so.6 (0x00007fdb72a4b000)
        libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007fdb72834000)
        libuuid.so.1 => /usr/lib64/libuuid.so.1 (0x00007fdb7262f000)
        /lib64/ld-linux-x86-64.so.2 (0x00007fdb7a70b000)
        libresolv.so.2 => /lib64/libresolv.so.2 (0x00007fdb72418000)
        libsasl2.so.3 => /usr/lib64/libsasl2.so.3 (0x00007fdb721fb000)
        libssl.so.1.0.0 => /lib64/libssl.so.1.0.0 (0x00007fdb71f8f000)
        libcrypto.so.1.0.0 => /lib64/libcrypto.so.1.0.0 (0x00007fdb71b33000)
        libaudit.so.1 => /usr/lib64/libaudit.so.1 (0x00007fdb71910000)
        libz.so.1 => /lib64/libz.so.1 (0x00007fdb716fa000)
        liblzma.so.5 => /usr/lib64/liblzma.so.5 (0x00007fdb714d1000)

I don't use a VM but a local machine, and my isp don't give access from external to my network - what I don't like, because I'd like to access from outer too. So unfortunately I can't give you access.

**Comment by tessus** [comment]
Everything looks perfectly fine from the output above. All dependent libraries are available to the hash library, at least at the first level. There can be multiple levels of indirection. e.g. one of those libs above might have problems to locate their dependent libs.

What about the `test_hash` binary? Does it run without errors?

Also, can you please attach the `db2diag.log` to this ticket? clear the db2diag.log, make a connect, run the command that gave you the error. I hope that the db2diag.log will have more info to investigate this further.

**Comment by tsschulz** [comment]
I can't compile it:
./maketest 
/tmp/ccAJXPeq.o: In function `sha256_base64':
hash.c:(.text+0x25e): undefined reference to `apr__SHA256_Init'
hash.c:(.text+0x27d): undefined reference to `apr__SHA256_Update'
hash.c:(.text+0x293): undefined reference to `apr__SHA256_Final'
/tmp/ccAJXPeq.o: In function `mk_hash':
hash.c:(.text+0x69c): undefined reference to `apr__SHA256_Init'
hash.c:(.text+0x6c7): undefined reference to `apr__SHA256_Update'
hash.c:(.text+0x6e0): undefined reference to `apr__SHA256_Final'

**Comment by tessus** [comment]
Hmmm, this makes no sense. If `./makertn` worked, so should `./maketest`.

One step forward, two steps back. Which versions of APR and APR-util are you using?
What about the other UDFs? Are they working? e.g. does `apr_sha1` work?

I'm still puzzled though. You have a problem with the sha256 UDF, which has nothing to do with APR. The sha256/sha512 UDFs/SPs make use of the system's crypt component and do not even involve APR, yet you get an error during the compile run for `test_hash` that indicates an old version of APR. Something is off, but I can't put my finger on what it is.

**Comment by tessus** [comment]
What about the db2diag.log? Can you please attach it here?

**Comment by tessus** [comment]
Also, can you please run `./maketest -v` and `./makertn -v` and paste the output here?

**Comment by tsschulz** [comment]
Ok, I did spend a little bit time into it. APR is version 1.5.3. I don't find a lib that proviceds the apr__* methods. So maybe its an old version. I'll try when I've some more time.

**Comment by tessus** [comment]
Still, it makes no sense that a UDF that has nothing to do with APR fails.

Maybe you do not have the devel packages installed (although in which case you could not have compiled the library in the first place). In any case, if you need help with compiling your own apr and apr-util versions (and using them for `makertn`), please let me know.

**Comment by tsschulz** [comment]
On which distributions is your tool tested?

**Comment by tessus** [comment]
I've tested the current release on Fedora and CentOS. I know that people are using it on Ubuntu and SuSE.

I've tested and run earlier releases on AIX, Solaris, MacOSX (when DB2 was still available for that platform). There should even be a version for Windows out there. I created a Windows library a long time ago, but never looked at that since.

The code has nothing really system dependent in it, but it requires  APR and APR-util. It _should_ work on all POSIX platforms without an issue.

Maybe you've a broken system or use SELinux and haven't set the context correctly for DB2. I really can't speculate on what is wrong with your system at this point, but I can tell you that there's no reason why it shouldn't work.

Without more information (the one I asked for several times) I don't know what I can do.

**Comment by tessus** [comment]
You can also have a look at the CI runs at https://travis-ci.org/tessus/db2-hash-routines

**Comment by tessus** [comment]
Any update on your end?

**Comment by tessus** [comment]
@tsschulz please let me know what the status is.

**Comment by tsschulz** [comment]
Hi, sorry. I was busy and not able to test it again. But I'll do it asap

**Comment by tsschulz** [comment]
Ok, what I did found out is that I have a problem with my distribution. There is a lib that links to another lib - which isn't existing and can't be installed. And this missing link is the reason that I get this error.

**Comment by tessus** [comment]
I'm sorry to hear that. If there's anything I can do, please let me know. As I mentioned before, I can give you detailed instructions on how to compile apr and apr-util.

Maybe there's a way to work around this lib that has a broken dependency.

If there's nothing else, please let me know, if I can close the ticket. Or you can close it yourself as well. It's up to you.
