### ISSUE TITLE
4K Limitation to calculate Hash

### ISSUE THREAD

**Issue by fdrgiit** [tessus/db2-hash-routines#19]
Hello All,

I am seeing here as per the description that all the code here has a 4KB limitation when it comes to calculating hash. So just wanted to ask if this is something can be changed by just changing the UDF definition in **registerDDL.sql** file or if there any other changes will be required as well.

Kindly share your comments.

**Comment by tessus** [comment]
The code itself does not have any hardcoded limitations. Thus changing the definition in the `register.ddl` should work.
It all depends on the memory that you allocate to UDFs in the database manager configuration. I haven't used DB2 for a while, so I don't know the parameter name off the top of my head. And there's an overall limit I think, but I might be wrong.

**Comment by fdrgiit** [comment]
@tessus Thanks for your comments. Basically I was referring to this:

**The argument can be a character string that is either a CHAR or VARCHAR not exceeding 4096 bytes**

I have CLOB columns which is greater than 4KB, where I would like to use PHP_MD5 to generate hash for the column data. Hence, my question, if there is a change I can do to achieve this.

Please comment.

**Comment by tessus** [comment]
I can't answer that for several reasons:

- CLOBs are handled differently in C code, but DB2 might do the conversion for you, in which case you are limited by the limitations of DB2.
- (var)char sizes are limited by the pagesize of the tablespace the table is in
- I did not create those routines to hash files or large amounts of data

I seriously doubt that you can hash a 1TB CLOB.

**Comment by fdrgiit** [comment]
@tessus Thanks for your comments.
We don't have that huge LOBs, just couple of megabytes. I will try the php_md5 function to see if that helps in getting the hash for these LOBs.

Additionally starting 11.1, Db2 does have this function : https://www.ibm.com/support/producthub/db2/docs/content/SSEPGG_11.5.0/com.ibm.db2.luw.sql.ref.doc/doc/r0061967.html

Which helps in generating MD5 HASH. Hence, i was looking for something similar in 10.5 as well.

**Comment by tessus** [comment]
I'm not sure how the function ind DB2 v11.1 handles CLOBs. Unfortunately I don't have access to the DB2 source code anymore.

Let me know, if you want to keep this open or close it.

**Comment by tessus** [comment]
Please let me know, if changing the `register.ddl` worked. This question might come up again.
