### ISSUE TITLE
Documentation page in StackOverFlow

### ISSUE THREAD

**Issue by angoca** [tessus/db2-hash-routines#8]
Hi Helmut, you can create a page in StackOverFlow Documentation: http://stackoverflow.com/documentation/db2/topics in order to promote how to use hashes in DB2. I will do the same for my projects.

**Comment by tessus** [comment]
Thanks for the info, but I do have extensive documentation in form of a [PDF manual](http://tessus.github.io/documentation/db2-hash-routines.pdf) and the [web site](http://tessus.github.io/db2-hash-routines/) provides a bunch of examples.

I do not intend to mirror this information somewhere else.

**Comment by tessus** [comment]
I might add a link to the documentation and the web site on stackoverflow at a later point.
