### ISSUE TITLE
user error? sha512('test') produces a different hash for every call

### ISSUE THREAD

**Issue by cons0l3** [tessus/db2-hash-routines#9]
Dear all,

I have successfully compiled and installed the db2-hash-routines into a db2-express-c 10.5.5 on centos. When running a 

`select sha512('test'), sha512('test') 
from sysibm.sysdummy1;
$6$SnwatgeG$F4SkijLEfDzARkKpREwD6MzgTSOUGkGdiFi9vkDB4KOU16XV4z1xVckyOu0wfyg17BZwMvkg391A25dtOYB0u/	$6$wbE5RBM0$2NrsyLA3CSksSnEBb/p28UT4/0Nn8g9TE25EODXPJdPMLYbREz2Ife9qxfdUD9P11dZnoA5AIEQ7OTYt4L85a.
`

I receive a different hash for every execution of the function with the same input. What do I miss?

I have tried all the other hash function. Same result. Every execution yields a new and different hash.

Cheers
Carsten

**Comment by tessus** [comment]
This is intended. The `sha256` UDF uses a random salt. The same result is only calculated for 
- apr_sha1
- apr_sha256
- php_md5

I primarily created those hash functions to insert passwords into DB2. To validate the hashes you can use the `validate_pw` function.

I used a random salt for security reasons. But maybe I should also add the option to specify the salt explicitly. 
Nobody ever requested this functionalty so I haven't really thought about it.

**Comment by cons0l3** [comment]
I should have checked the source in the first place LoL. My use case is generating hashes for capturing data change and generating primary keys in a data vault. So I would like to have non-randomized hashes ;-) Adding the posibility to explicitly set a salt would be great. Maybe adding the fact of a randomized salt to the documentation would also benefit - I hope I did not missed and it is already written.

**Comment by tessus** [comment]
It's not the coding, but testing the changes, writing documentation, ...
I also don't have access to an AIX box anymore, so I can't even test on AIX.

There are also other things to consider: what should be the behaviour, if an empty string (not NULL) is specified as the salt? Stuff like that.

Anyway, I'll open a separate ticket. I should be able to get it done within the next 2 weeks.
